### ISSUE TITLE
the package is not registered on Packagist

### ISSUE THREAD

**Issue by stof** [zf-fr/zfr-oauth2-server-module#22]
I don't know whether it is expected, but this is confusing

**Comment by bakura10** [comment]
Hmmm... it is no? https://packagist.org/packages/zfr/zfr-oauth2-server-module

**Comment by stof** [comment]
OK, it looks like an issue in the Packagist search: https://packagist.org/search/?q=%20zfr%2Fzfr-oauth2-server-module
