### ISSUE TITLE
math dependancy

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-oauth2-server-module#26]
apparently "copy-paste is better (than dependancies)" ...

applies only to when php <= 7.0, 

why don't we include this?
https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/ResponseType/AccessToken.php#L115 or https://github.com/zendframework/zend-math/blob/master/src/Rand.php#L42

to remove dependency to zend-math?

note: we should ad suggestions to ext-openssl and ext-crypt
note: I don't like '+' chars very much as you have to urlencode or send as 'multipart/form-data'

**Comment by bakura10** [comment]
We don't need that. PHP7 has random_bytes (http://php.net/random_bytes).

**Comment by basz** [comment]
we will depend on php7 for sure? not waiting on what apigility 2.0 will depend on? I saw (somewhere you asked mop about this)

**Comment by bakura10** [comment]
I will ask him tonight, but I'd honestly like to be PHP7+ only :).
