### ISSUE TITLE
Bump the constraints in composer.json

### ISSUE THREAD

**Issue by macnibblet** [zf-fr/zfr-oauth2-server-module#27]
The current versions are keeping us to an old versions of libraries that don't fully support 7.1 mainly the doctrine/doctrine-orm-module

**Comment by bakura10** [comment]
Hi !

It's been some time I didn't use it actually and @basz took the lead of those projects. The fact that the next version of ZfrOAuth2Server is not compatible (refactored for middlewares) make me think that this module may become a bit useless.

@basz, what is the ETA on tagging 0.8 in ZfrOAuth2Server and then updating this module if required?

**Comment by basz** [comment]
Hello! Hmm.. wasn't conciously aware this module still existed :-)

0.8 of ZfrOAuth2Server could be tagged soon (I'm still using master'. There are a few tests I wanted to complete before doing that. But as said work must be done to get this project compatible with 0.8 and I wasn't planning on doing that. 

I propose we create a legacy branch of ZfrOAuth2Server and update that to remove the mentioned contraints? That shouldn't be to much work...

cc. @prolic

**Comment by prolic** [comment]
@basz :+1:

**Comment by basz** [comment]
@macnibblet should be resolved
